services:
  # Order service
  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    container_name: saga_order_service
    ports:
      - "8001:8000"
    volumes:
      - ./order:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - saga-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      order-db:
        condition: service_healthy

  # Customer service
  customer-service:
    build:
      context: ./customer
      dockerfile: Dockerfile
    container_name: saga_customer_service
    ports:
      - "8002:8000"
    volumes:
      - ./customer:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - saga-network
    depends_on:
      customer-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  # Order database
  order-db:
    image: postgres:15.15-alpine3.22
    container_name: saga_order_db
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password232323
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d order_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    networks:
      - saga-network

  # Customer database
  customer-db:
    image: postgres:15.15-alpine3.22
    container_name: saga_customer_db
    environment:
      - POSTGRES_DB=customer_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password232323
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d customer_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - customer_postgres_data:/var/lib/postgresql/data
    networks:
      - saga-network

  # Shared RabbitMQ for saga communication
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: saga_rabbitmq
    ports:
      - "5671:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - saga-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  order_postgres_data:
  customer_postgres_data:
  rabbitmq_data:

networks:
  saga-network:
    driver: bridge
