services:
  redis:
    image: "redis:latest"
    container_name: "redis_service"
    ports:
      - "6374:6379"
    networks:
      - service_discovery_network

  discovery-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "service_discovery_app"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    networks:
      - service_discovery_network

networks:
  service_discovery_network:
    driver: bridge
